apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: ghdefaults
resources:
  - deployment.k8s.yaml
  - ingressroute.k8s.yaml
  - service.k8s.yaml
  - serviceaccount.k8s.yaml
